# -*- coding: utf-8 -*-
import re, json
import os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC=os.path.join(ROOT,'index.html'); DST=os.path.join(ROOT,'en','index.html')
s=open(SRC,encoding='utf-8').read()

TEXT={
'CMTeam — Triathlon, Corrida e Endurance':'CMTeam — Triathlon, Running & Endurance Coaching',
'Grátis':'Free',
'Baixe o e-book':'Download the e-book',
', de San Palma':', by San Palma (in Portuguese)',
'Baixar agora →':'Download now →',
'Manifesto':'Manifesto','Método ECO':'ECO Method','Treinadores':'Coaches','Livros':'Books','Treinos':'Training',
'Fale conosco':'Contact us',
'Triathlon · Corrida · Endurance':'Triathlon · Running · Endurance',
'Aqui, cada treino tem motivo.':'Every session has a reason.',
'Assessoria especializada em triathlon, corrida e esportes de endurance. Metodologia própria, acompanhamento próximo e visão de longo prazo — do iniciante ao competitivo.':'Triathlon, running and endurance coaching. Our own methodology, close guidance and a long-term vision — from first-timers to competitive athletes.',
'Falar no WhatsApp':'Message us on WhatsApp','Conheça o método':'Discover the method',
'anos de CMTeam':'years of CMTeam','atletas treinados':'athletes coached','países':'countries','continentes':'continents',
'Nossos atletas em':'Our athletes at',
'Ironman Itália — Emilia-Romagna':'Ironman Italy — Emilia-Romagna','Maratona de Buenos Aires':'Buenos Aires Marathon',
'O Manifesto CMTeam':'The CMTeam Manifesto',
'Não somos um time feito de resultados. Somos um time feito de processos.':'We are not a team built on results. We are a team built on process.',
'A CMTeam nasceu da vontade de construir algo diferente: um espaço onde a performance é consequência, não cobrança. Onde a paciência é tão valorizada quanto a intensidade, e onde cada atleta aprende que evoluir é um caminho, não uma meta de calendário.':'CMTeam was born from the desire to build something different: a place where performance is a consequence, not a demand. Where patience is valued as much as intensity, and where every athlete learns that progress is a path, not a date on the calendar.',
'Treinamos com ciência, mas também com alma. Com planilha, mas com propósito. Com técnica, mas com verdade. Acreditamos que disciplina é mais poderosa do que motivação, e que ser consistente é a forma mais pura de ser forte.':'We train with science, but also with soul. With a plan, but with purpose. With technique, but with honesty. We believe discipline is more powerful than motivation, and that consistency is the purest form of strength.',
'Nosso objetivo não é ser o melhor time. É ser o time que não desiste de ser melhor.':'Our goal is not to be the best team. It is to be the team that never stops trying to be better.',
'Nada grande nasce apressado. A consistência vale mais do que o talento, e cada adaptação precisa de tempo para se tornar parte de quem você é. Ser paciente é saber esperar enquanto se constrói.':'Nothing great is born in a hurry. Consistency is worth more than talent, and every adaptation needs time to become part of who you are. Being patient means waiting while you build.',
'O aprendizado nunca termina. Humildade não é se diminuir: é ter a grandeza de continuar curioso, de ouvir, de respeitar — e entender que o sucesso individual só tem valor quando soma ao coletivo.':'Learning never ends. Humility is not making yourself smaller: it is having the greatness to stay curious, to listen, to respect — and to understand that individual success only matters when it adds to the team.',
'Ser forte não é vencer sempre. É continuar quando não se tem mais certeza. A força verdadeira não se mede no FTP, no pace ou no ranking: se mede na capacidade de recomeçar.':'Being strong is not winning every time. It is carrying on when you are no longer sure. True strength is not measured in FTP, pace or rankings: it is measured by the ability to start again.',
'Metodologia própria':'Our own methodology',
'O ECO parte de um princípio claro: o corpo evolui melhor quando o esforço é bem distribuído, respeita o momento do atleta e evita o desgaste silencioso causado por excesso de intensidade mal aplicada.':'ECO starts from a clear principle: the body improves best when effort is well distributed, respects where the athlete is right now, and avoids the silent wear caused by too much poorly applied intensity.',
'Base aeróbia sólida':'A solid aerobic base','A base é prioridade. É ela que sustenta toda a evolução.':'The base comes first. It supports every step of progress.',
'Intensidade estratégica':'Strategic intensity','Intensidade usada de forma estratégica, não emocional.':'Intensity used strategically, not emotionally.',
'Ciclos com lógica':'Cycles with logic','Ciclos organizados para construir, consolidar e realizar.':'Cycles organized to build, consolidate and perform.',
'Carga da vida real':'Real-life load','Carga ajustada ao treino, ao trabalho, à família e à recuperação.':'Load adjusted to training, work, family and recovery.',
'Tudo é individualizado, respeitando os princípios do treinamento: individualidade biológica, adaptação, relação volume × intensidade, sobrecarga e especificidade.':'Everything is individualized, following the principles of training: biological individuality, adaptation, volume × intensity, overload and specificity.',
'Como trabalhamos':'How we work','Planejamento claro. Acompanhamento de perto.':'Clear planning. Close follow-up.',
'Todos os treinos são prescritos e acompanhados pelo TrainingPeaks. O feedback pós-treino faz parte ativa do processo e orienta as decisões semana a semana.':'Every session is prescribed and tracked on TrainingPeaks. Post-workout feedback is an active part of the process and guides our decisions week by week.',
'Planejamento semanal claro e organizado':'Clear, organized weekly planning','Treinos explicados, com objetivo e orientação prática':'Every workout explained, with a purpose and practical guidance','Acompanhamento contínuo e ajustes frequentes':'Ongoing follow-up and frequent adjustments','Feedback direto dentro do aplicativo':'Direct feedback inside the app',
'Modalidades':'Disciplines','Do primeiro 5 km ao Ironman.':'From your first 5K to Ironman.',
'Do sprint ao Ironman, com natação, bike e corrida integradas num só plano.':'From sprint to Ironman, with swim, bike and run integrated in one plan.',
'Corrida de rua':'Road running','Do 5 km à maratona, com foco em ritmo, economia e consistência.':'From 5K to the marathon, focused on pace, economy and consistency.',
'Trail e montanha':'Trail & mountain','Subidas, descidas e terreno técnico, com preparação específica para cada prova.':'Climbs, descents and technical terrain, with race-specific preparation.',
'Ultramaratona':'Ultramarathon','Longas distâncias com estratégia de ritmo, nutrição e resistência mental.':'Long distances with pacing strategy, nutrition and mental endurance.',
'Duas trajetórias. Uma convicção.':'Two journeys. One conviction.',
'Por trás da CMTeam existem duas trajetórias construídas no esporte de alto rendimento, guiadas pela mesma ideia: performance só faz sentido quando vem acompanhada de processo, consciência e longevidade.':'Behind CMTeam are two journeys built in high-performance sport, guided by the same idea: performance only makes sense when it comes with process, awareness and longevity.',
'CMTeam é Carla Moreno Team.':'CMTeam stands for Carla Moreno Team.',
'O time nasceu de duas pessoas, San e Carla, e de um grupo que acreditou que a ciência e a alma podem caminhar juntas.':'The team was born from two people, San and Carla, and from a group that believed science and soul can go hand in hand.',
'Co-fundador e Head Coach':'Co-founder & Head Coach',
'Treinador desde 2003 e atleta há mais de 30 anos, com certificações USA Triathlon, IRONMAN e TrainingPeaks. Conduziu Carla Moreno em sua fase de supremacia no triathlon nacional — anos vencendo as principais provas olímpicas do Brasil e mais de seis temporadas invicta em Miami. Já classificou atletas para mundiais ITU, Ironman 70.3 e Ironman 140.6 e foi treinador da delegação brasileira em competições internacionais. Especialista em Fisiologia do Esforço e Prescrição do Treinamento, é o criador do Método ECO.':'Coaching since 2003 and an athlete for more than 30 years, certified by USA Triathlon, IRONMAN and TrainingPeaks. He coached Carla Moreno through her era of dominance in Brazilian triathlon — years winning Brazil’s top Olympic-distance races and more than six seasons unbeaten in Miami. He has qualified athletes for ITU, Ironman 70.3 and Ironman 140.6 world championships and coached the Brazilian national team at international events. A specialist in exercise physiology and training prescription, he is the creator of the ECO Method.',
'“O contato com a ciência não substitui o campo. Ele qualifica o olhar sobre o campo.”':'“Science does not replace time in the field. It sharpens the way we see the field.”',
# --- ECO section (v2) and updated bios ---
'Mais do que uma sequência de treinos, o ECO é um sistema. Em toda fase da periodização, o atleta recebe estímulos de intensidade diferentes — mais altos ou mais baixos, mais longos ou mais curtos — conforme a prova-alvo e o momento do treinamento.':'ECO is more than a sequence of workouts: it is a system. In every phase of the periodization, the athlete receives different intensity stimuli — higher or lower, longer or shorter — according to the target race and the moment in training.',
'Nunca há um período totalmente leve ou totalmente forte. A carga varia em ondas, mas o esforço nunca desaparece.':'There is never a fully easy or fully hard period. Load moves in waves, but the effort never disappears.',
'Os fundamentos':'The foundations',
'Ciclos ATR':'ATR cycles',
'Acumulação, Transformação e Realização: primeiro volume e base aeróbia, depois ritmo e limiar, por fim o polimento para o dia da prova. Cada ciclo respeita o tempo que o corpo precisa para consolidar os estímulos.':'Accumulation, Transformation and Realization: first volume and aerobic base, then pace and threshold, and finally the taper for race day. Each cycle respects the time the body needs to consolidate the work.',
'Intensidade piramidal':'Pyramidal intensity',
'Base larga em zonas submáximas (A1, A2 e A3) e Vo2 pontual e controlado. Muito volume sustentável, adaptação constante e nada de esgotamento precoce.':'A wide base in submaximal zones (A1, A2 and A3) and occasional, controlled VO2 work. Plenty of sustainable volume, constant adaptation and no early burnout.',
'O maior ativo de um atleta de endurance. Mesmo nas fases mais intensas, os treinos de A1 e A2 continuam presentes. Eles são o cimento da casa.':'The greatest asset of an endurance athlete. Even in the most intense phases, A1 and A2 sessions stay in the plan. They are the cement that holds the house together.',
'A mentalidade':'The mindset',
'ECO também é Execução, Constância e Observação.':'ECO is also Execution, Consistency and Observation.',
'Execução':'Execution','Fazer o treino como planejado, com presença e foco no processo.':'Do the session as planned, fully present and focused on the process.',
'Constância':'Consistency','Repetir com propósito, mesmo nos dias sem motivação.':'Repeat with purpose, even on days without motivation.',
'Observação':'Observation','Ajustar com sabedoria, escutar o corpo, reconhecer padrões.':'Adjust wisely, listen to your body, recognize patterns.',
'Treinar por treinar não muda ninguém. Treinar com consciência muda tudo.':'Training for the sake of training changes no one. Training with awareness changes everything.',
'Aqui não existem treinos soltos. Existe um sistema com propósito.':'There are no random workouts here. There is a system with a purpose.',
'Tudo o que você faz hoje está conectado ao que virá daqui a 3 semanas, 3 meses, 1 ano. O ECO serve do iniciante ao avançado e se adapta à realidade de cada atleta: treino, trabalho, família e recuperação.':'Everything you do today is connected to what comes 3 weeks, 3 months, 1 year from now. ECO works for beginners and advanced athletes alike, and adapts to each athlete’s reality: training, work, family and recovery.',
'Treinador desde 2003 e atleta há mais de 30 anos. Bacharel em Educação Física, especialista em Fisiologia do Exercício e Prescrição de Treinamento e pós-graduado em Corrida de Montanha. Foi treinador da Seleção Brasileira de Triathlon em Mundiais ITU, Copas do Mundo e Jogos Pan-Americanos, Head Coach da delegação brasileira nos Mundiais de Budapeste e Pequim e integrou o board da Confederação Brasileira de Triathlon (CBTri).':'Coaching since 2003 and an athlete for over 30 years. Degree in Physical Education, specialist in Exercise Physiology and Training Prescription, with a postgraduate degree in Mountain Running. He coached the Brazilian National Triathlon Team at ITU World Championships, World Cups and the Pan American Games, was Head Coach of the Brazilian delegation at the World Championships in Budapest and Beijing, and served on the board of the Brazilian Triathlon Confederation (CBTri).',
'Conduziu Carla Moreno em sua fase de supremacia no triathlon nacional e já classificou atletas para mundiais ITU, IRONMAN 70.3 e IRONMAN. Com training camps na Europa, Oceania e Américas do Norte e do Sul, é o criador do Método ECO e responsável pela periodização de todo o time.':'He coached Carla Moreno through her era of dominance in Brazilian triathlon and has qualified athletes for ITU, IRONMAN 70.3 and IRONMAN World Championships. With training camps in Europe, Oceania, and North and South America, he created the ECO Method and leads the periodization of the whole team.',
'Campeã Mundial Júnior logo na primeira temporada internacional e bicampeã mundial (Triathlon Júnior e Aquathlon). Integrou a Seleção Brasileira por 14 anos consecutivos e representou o Brasil em dois Jogos Olímpicos — Sydney 2000 e Atenas 2004 —, com medalhas pan-americanas, vitórias em Copas do Mundo e o título do IRONMAN 70.3 Brasil.':'Junior World Champion in her very first international season and two-time world champion (Junior Triathlon and Aquathlon). She was on the Brazilian National Team for 14 consecutive years and represented Brazil at two Olympic Games — Sydney 2000 and Athens 2004 —, with Pan American medals, World Cup wins and the IRONMAN 70.3 Brazil title.',
'Com oito títulos, é a maior vencedora da história do Triathlon Internacional de Santos, entre homens e mulheres, e detém o recorde absoluto de mais de 50 etapas vencidas no Troféu Brasil de Triathlon. Em Miami, ficou invicta por cinco temporadas consecutivas no Trilogy Triathlon: mais de 100 provas entre 2018 e 2023, com 98% de vitórias.':'With eight titles, she is the winningest athlete in the history of the Santos International Triathlon, men and women combined, and holds the all-time record of more than 50 stage wins in the Troféu Brasil de Triathlon. In Miami, she went unbeaten for five consecutive seasons in the Trilogy Triathlon series: more than 100 races between 2018 and 2023, winning 98% of them.',
'Hoje atua diretamente no atendimento e na orientação dos atletas, traduzindo o treinamento em decisões práticas, estratégia de prova e equilíbrio entre esporte e vida pessoal.':'Today she works directly with every athlete, turning training into practical decisions, race strategy and a healthy balance between sport and personal life.',
# --- online section + credentials (v3) ---
'CMTeam — Assessoria de Triathlon e Corrida | Online e Miami':'CMTeam — Triathlon & Running Coaching | Online and Miami',
'Treino online':'Online coaching','De qualquer lugar do mundo.':'From anywhere in the world.',
'Quem treina à distância recebe o mesmo acompanhamento de quem está no grupo em Miami: planilha individual, feedback diário e uma atleta olímpica do seu lado. A CMTeam está presente em mais de 25 países.':'Athletes who train remotely get the same follow-up as those in our Miami group: an individual plan, daily feedback and an Olympian by your side. CMTeam has athletes in more than 25 countries.',
'De segunda a sábado':'Monday to Saturday','Carla Moreno no seu WhatsApp.':'Carla Moreno on your WhatsApp.',
'Dúvidas, ajustes de treino e estratégia de prova direto com a Carla, atleta olímpica e bicampeã mundial, com dedicação integral aos atletas do time. Ser atendido por quem viveu o esporte no mais alto nível faz diferença.':'Questions, training adjustments and race strategy straight with Carla, an Olympian and two-time world champion who is fully dedicated to the team’s athletes. Being coached by someone who lived the sport at the highest level makes a difference.',
'Quero treinar online':'I want to train online',
'Sua planilha, toda semana':'Your plan, every week','Planejamento individual feito pelo San e publicado semanalmente no TrainingPeaks, com as instruções de cada dia e de cada modalidade.':'An individual plan built by San and published weekly on TrainingPeaks, with instructions for each day and each discipline.',
'Seu feedback move o plano':'Your feedback drives the plan','Cada comentário pós-treino chega na hora para o San e orienta os ajustes da semana seguinte.':'Every post-workout comment reaches San right away and shapes the adjustments for the following week.',
'Zonas sob medida':'Zones made for you','Testes para definição das suas zonas de treinamento, a base de toda a prescrição.':'Tests to set your training zones, the foundation of every prescription.',
'Treinador desde 2003 e atleta há mais de 30 anos. Bacharel em Educação Física e Esportes, especialista em Fisiologia do Exercício e Prescrição de Treinamento e pós-graduado em Corrida de Montanha.':'Coaching since 2003 and an athlete for over 30 years. Degree in Physical Education and Sports, specialist in Exercise Physiology and Training Prescription, with a postgraduate degree in Mountain Running.',
'Conduziu Carla Moreno em sua fase de supremacia no triathlon nacional e organizou training camps na Europa, Oceania e Américas do Norte e do Sul. É o criador do Método ECO e responsável pela periodização de todo o time.':'He coached Carla Moreno through her era of dominance in Brazilian triathlon and has run training camps in Europe, Oceania, and North and South America. He created the ECO Method and leads the periodization of the whole team.',
'Na carreira':'Career highlights',
'Treinador da Seleção Brasileira de Triathlon em Mundiais ITU e Copas do Mundo':'Coach of the Brazilian National Triathlon Team at ITU World Championships and World Cups',
'Treinador nos Jogos Pan-Americanos Rio 2007':'Coach at the Rio 2007 Pan American Games',
'Head Coach da delegação brasileira nos Mundiais ITU de Budapeste 2010 e Pequim 2011':'Head Coach of the Brazilian delegation at the ITU World Championships in Budapest 2010 and Beijing 2011',
'Membro do board da CBTri como Diretor de Materiais e Tecnologia':'Board member of the Brazilian Triathlon Confederation (CBTri) as Director of Equipment and Technology',
'Atletas profissionais classificados para Mundiais, Copas do Mundo e Jogos Pan-Americanos':'Professional athletes qualified for World Championships, World Cups and the Pan American Games',
'Atletas amadores classificados para Mundiais de todas as distâncias, incluindo o Mundial IRONMAN 70.3 e o IRONMAN World Championship, em Kona':'Age-group athletes qualified for World Championships at every distance, including the IRONMAN 70.3 World Championship and the IRONMAN World Championship in Kona',
'Campeã Mundial Júnior em 1996, logo na primeira temporada internacional. Integrou a Seleção Brasileira por 14 anos consecutivos e representou o Brasil em dois Jogos Olímpicos — Sydney 2000 e Atenas 2004 — e em três Jogos Pan-Americanos.':'Junior World Champion in 1996, in her very first international season. She was on the Brazilian National Team for 14 consecutive years and represented Brazil at two Olympic Games — Sydney 2000 and Athens 2004 — and at three Pan American Games.',
'Em Miami, segue competindo em alto nível: invicta por cinco temporadas consecutivas no Trilogy Triathlon, com mais de 100 provas entre 2018 e 2023 e 98% de vitórias.':'In Miami, she still races at a high level: unbeaten for five consecutive seasons in the Trilogy Triathlon series, with more than 100 races between 2018 and 2023 and a 98% win rate.',
'Principais conquistas':'Major titles',
'Campeã Mundial de Triathlon Júnior (1996)':'Junior Triathlon World Champion (1996)',
'Prata nos Jogos Pan-Americanos de Winnipeg (1999)':'Silver medal at the Winnipeg Pan American Games (1999)',
'Campeã Mundial de Aquathlon (2003)':'Aquathlon World Champion (2003)',
'Campeã do IRONMAN 70.3 Brasil (2007)':'IRONMAN 70.3 Brazil Champion (2007)',
'Campeã Brasileira de Triathlon (2010)':'Brazilian Triathlon Champion (2010)',
'Vice-campeã Mundial nos Jogos Mundiais Militares (2011)':'World runner-up at the Military World Games (2011)',
'Bicampeã da Copa do Mundo (México e Brasil)':'Two-time World Cup winner (Mexico and Brazil)',
'Bicampeã Pan-Americana (Brasil e México)':'Two-time Pan American Champion (Brazil and Mexico)',
'Oito vezes campeã do Troféu Brasil de Triathlon, recordista absoluta de etapas vencidas':'Eight-time Troféu Brasil de Triathlon champion, all-time record holder for stage wins',
'Oito vitórias no Triathlon Internacional de Santos':'Eight wins at the Santos International Triathlon',
'Calendário do time 2027':'2027 team calendar',
'Onde o time se encontra.':'Where the team meets.',
'Estas são as provas-alvo oficiais da CMTeam em 2027. Nas provas com suporte confirmado, o time está lá com você, da preparação à linha de chegada.':'These are the official CMTeam target races for 2027. At races with confirmed support, the team is there with you, from preparation to the finish line.',
'Inscrições para IRONMAN e IRONMAN 70.3 têm fechado cada vez mais cedo. Se uma dessas provas está nos seus planos, defina o objetivo e garanta sua vaga com antecedência.':'IRONMAN and IRONMAN 70.3 registrations have been closing earlier and earlier. If one of these races is in your plans, set your goal and secure your entry early.',
'Suporte do time confirmado':'Team support confirmed',
'Suporte a confirmar':'Support to be confirmed',
'31 jan':'Jan 31',
'18–20 mar':'Mar 18–20',
'22–25 abr':'Apr 22–25',
'8 mai':'May 8',
'4–6 jun':'Jun 4–6',
'Out':'Oct','Nov':'Nov','Cozumel, Quintana Roo · México':'Cozumel, Quintana Roo · Mexico',
'Miami, Flórida · EUA':'Miami, Florida · USA',
'São Bento do Sapucaí, SP · Brasil':'São Bento do Sapucaí, SP · Brazil',
'Auburn, Califórnia · EUA':'Auburn, California · USA',
'Panama City Beach, Flórida · EUA':'Panama City Beach, Florida · USA',
'Chattanooga, Tennessee · EUA':'Chattanooga, Tennessee · USA',
'Sacramento, Califórnia · EUA':'Sacramento, California · USA',
'O suporte nas provas a confirmar depende do número de atletas inscritos e do interesse do grupo. As datas oficiais do IRONMAN California e do IRONMAN Cozumel 2027 ainda serão divulgadas. Vai correr alguma delas?':'Support at the races still to be confirmed depends on the number of registered athletes and the interest of the group. The official 2027 dates for IRONMAN California and IRONMAN Cozumel are yet to be announced. Racing one of them?',
'Fale com a gente':'Talk to us',
'Dúvidas, ajustes e feedbacks direto com a Carla, que trabalha lado a lado com o San. Você não fica sem resposta e mantém o foco nos treinos. E do outro lado está uma atleta olímpica.':'Questions, adjustments and feedback straight with Carla, who works side by side with San. You are never left without an answer, and you keep your focus on training. And on the other end is an Olympian.',
'Você chama a Carla':'You message Carla',
'no WhatsApp, de segunda a sábado':'on WhatsApp, Monday to Saturday',
'Ela alinha com o San':'She aligns with San',
'tudo passa pela supervisão do coach':'everything goes through the coach',
'O ajuste entra no seu plano':'The change goes into your plan',
'sempre dentro da sua periodização individual':'always within your individual periodization',
'Quero treinar com a CMTeam':'I want to train with CMTeam',
'Planos':'Plans',
'Online, de qualquer lugar, ou presencial em Miami.':'Online from anywhere, or in person in Miami.',
'Conte seu objetivo e sua rotina, e a gente monta com você o melhor caminho.':'Tell us your goal and your routine, and we will build the best path with you.',
'Preciso ser experiente para treinar com a CMTeam?':'Do I need experience to train with CMTeam?',
'Não. Treinamos do primeiro 5 km ao Ironman. O plano parte do seu momento, da sua rotina e do seu objetivo, seja ele começar, evoluir ou competir.':'No. We coach everyone from a first 5K to Ironman. Your plan starts from where you are, your routine and your goal, whether that is getting started, improving or competing.',
'Funciona se eu não moro em Miami?':'Does it work if I don’t live in Miami?',
'Sim. O acompanhamento online é completo: planilha individual no TrainingPeaks, feedback diário e a Carla no WhatsApp, de segunda a sábado. Temos atletas em mais de 25 países.':'Yes. Online coaching is complete: an individual plan on TrainingPeaks, daily feedback and Carla on WhatsApp, Monday to Saturday. We have athletes in more than 25 countries.',
'Quais modalidades vocês treinam?':'Which sports do you coach?',
'Triathlon, corrida de rua, trail e montanha e ultramaratona, sempre com a metodologia ECO.':'Triathlon, road running, trail and mountain running, and ultramarathon, always with the ECO methodology.',
'Como é o começo?':'How does it start?',
'Primeiro a gente conversa sobre seu objetivo e sua rotina. Depois você preenche um cadastro completo, com saúde, histórico e disponibilidade, e faz os testes para definição das suas zonas. A partir daí, sua planilha chega toda semana no TrainingPeaks.':'First we talk about your goal and your routine. Then you fill in a complete intake form, covering health, history and availability, and do the tests to set your training zones. From then on, your plan arrives every week on TrainingPeaks.',
'Preciso de relógio com GPS?':'Do I need a GPS watch?',
'Ajuda bastante, porque os treinos vão direto para o TrainingPeaks e o feedback fica mais preciso. Se você ainda não tem, a gente orienta na conversa.':'It helps a lot, because your workouts sync straight to TrainingPeaks and the feedback is more precise. If you don’t have one yet, we will guide you when we talk.',
'Quanto custa?':'How much does it cost?',
'Depende do formato, online ou presencial, e do que faz sentido para o seu objetivo. Chame a gente no WhatsApp e montamos juntos o melhor caminho.':'It depends on the format, online or in person, and on what makes sense for your goal. Message us on WhatsApp and we will build the best path together.',
'A ciência de San Palma, criador do Método ECO. A experiência olímpica de Carla Moreno. Online, de qualquer lugar, e presencial em Miami.':'The science of San Palma, creator of the ECO Method. The Olympic experience of Carla Moreno. Online from anywhere, and in person in Miami.',
'Perguntas frequentes':'FAQ',
'Antes de começar.':'Before you start.',
'Ficou alguma dúvida?':'Still have a question?',
'Fale com a gente no WhatsApp':'Message us on WhatsApp',
'Treino online':'Online coaching',
'Calendário 2027':'2027 calendar',
'Ver os planos →':'See the plans →',
'por San Palma':'by San Palma',
'Também é escritor: autor de ':'He is also a writer: author of ',
', escreve toda semana para os atletas do time, e o próximo livro, Nossa Jornada 2026, já está a caminho.':', he writes every week for the team’s athletes, and his next book, Nossa Jornada 2026, is on the way.',
' e do livro de bolso ':' and the pocket book ',
'Autor dos livros Nossa Jornada 2025 e A cabeça corre primeiro':'Author of the books Nossa Jornada 2025 and A cabeça corre primeiro',
'Co-fundadora e Treinadora':'Co-founder & Coach',
'Campeã Mundial Júnior de Triathlon, integrou a Seleção Brasileira por 14 anos consecutivos e representou o Brasil em dois Jogos Olímpicos — Sydney 2000 e Atenas 2004 —, com títulos mundiais, pan-americanos e vitórias em Copas do Mundo. Hoje atua diretamente no atendimento e na orientação dos atletas, traduzindo o treinamento em decisões práticas, estratégia de prova e equilíbrio entre esporte e vida pessoal.':'Junior Triathlon World Champion, she was part of the Brazilian national team for 14 consecutive years and represented Brazil at two Olympic Games — Sydney 2000 and Athens 2004 — with world and Pan American titles and World Cup wins. Today she works directly with our athletes, turning training into practical decisions, race strategy and balance between sport and personal life.',
'“Carregar meu nome no time é uma honra que nunca se tornou rotina. A CMTeam é, sim, o meu nome, mas, mais do que isso, é a soma de todas as pessoas que decidiram acreditar no mesmo propósito.”':'“Having my name on this team is an honor that has never become routine. CMTeam is my name, yes — but more than that, it is the sum of everyone who chose to believe in the same purpose.”',
'Livros e textos':'Books & writing','Ensinar o atleta também é treino.':'Teaching the athlete is training too.',
'Nossa missão vai além da planilha: queremos que cada atleta entenda o que está fazendo e por quê. Por isso, o conhecimento do time circula toda semana no grupo exclusivo dos atletas — e, ao fim de cada ano, vira livro, registrando a vivência real do que é treinado e aprendido dentro da CMTeam.':'Our mission goes beyond the training plan: we want every athlete to understand what they are doing and why. That is why knowledge flows every week in our athletes’ private group — and, at the end of each year, it becomes a book (in Portuguese) that records what is truly trained and learned inside CMTeam.',
'Segunda':'Monday','Texto reflexivo sobre treino, processo e mentalidade':'A reflective piece on training, process and mindset',
'Quarta':'Wednesday','Infográficos técnicos e educativos':'Technical, educational infographics',
'Sexta':'Friday','Textos diretos, aplicáveis ao treino do dia a dia':'Straightforward pieces you can apply to everyday training',
'Publicado':'Published',
'Reflexões, aprendizados e os pilares que moldaram um ano de treinos. O primeiro livro da CMTeam reúne os textos escritos para o time ao longo de 2025.':'Reflections, lessons and the pillars that shaped a year of training. CMTeam’s first book brings together the texts written for the team throughout 2025. In Portuguese.',
'Amazon Brasil':'Amazon Brazil','Amazon EUA':'Amazon US',
'Saindo do forno':'Coming soon',
'Construído semana a semana a partir dos textos de segunda de 2026. Cada texto que o time recebe hoje é uma página do próximo livro.':'Built week by week from our 2026 Monday texts. Every piece the team receives today is a page of the next book.',
'Quero ser avisado →':'Notify me →',
'E-book gratuito':'Free e-book',
'Lições rápidas para uma mente mais forte no esporte. Um livro de bolso sobre dor, disciplina, fracasso e os pilares da força mental, com um checklist de 8 hábitos para colocar em prática.':'Quick lessons for a stronger mind in sport. A pocket book on pain, discipline, failure and the pillars of mental strength, with a checklist of 8 habits to put into practice. Available in Portuguese.',
'Nome':'Name','Baixar grátis':'Get it free','Baixar o livro (PDF)':'Download the book (PDF)',
'8 hábitos para uma mente forte':'8 habits for a strong mind',
'Comece o dia com clareza, não com pressa':'Start the day with clarity, not rush','Antes de abrir o celular, respire e lembre por que você está treinando.':'Before you open your phone, breathe and remember why you are training.',
'Treine mesmo sem vontade':'Train even when you don’t feel like it','Quando você escolhe a execução, não a emoção, a mente entende quem manda.':'When you choose execution over emotion, your mind learns who is in charge.',
'Corrija a voz interna':'Correct your inner voice','Pegou o “não dá”? Interrompa, respire, troque a frase.':'Caught yourself thinking “I can’t”? Stop, breathe, change the sentence.',
'Execute bem o treino mais simples':'Nail the simplest session','Foco total até no regenerativo. É isso que constrói excelência.':'Full focus even on the recovery run. That is what builds excellence.',
'Aceite os dias ruins':'Accept the bad days','Não se sabote por um treino fraco. Recomece no dia seguinte, sem drama.':'Don’t sabotage yourself over one weak session. Start again tomorrow, no drama.',
'Silêncio ao invés de comparação':'Silence over comparison','Enquanto os outros postam, você trabalha. Sua evolução acontece longe da vitrine.':'While others post, you work. Your progress happens away from the spotlight.',
'Feche o dia com uma pergunta':'End the day with one question','“Hoje eu fui quem eu quero ser?” Se sim, celebre. Se não, aprenda.':'“Was I today who I want to be?” If yes, celebrate. If not, learn.',
'Confie no seu treinador e no processo':'Trust your coach and the process','Seu treinador vê o que você ainda não vê. Ouça, execute, aprenda.':'Your coach sees what you can’t see yet. Listen, execute, learn.',
'Treinos presenciais':'In-person training','Terça':'Tuesday','Corrida 6h00–7h20 · Natação 7h20–8h00':'Run 6:00–7:20am · Swim 7:20–8:00am','Bike 6h00–8h00':'Bike 6:00–8:00am','Quinta':'Thursday','Sábado':'Saturday','Longo de corrida · Natação em águas abertas':'Long run · Open-water swim',
'# Transição':'# Brick','Todo mês tem transição e simulado de prova.':'Every month: brick sessions and race simulations.',
'Uma ou duas vezes por mês, na Tribeach: natação + corrida, bike + corrida ou o triathlon completo. Técnica de execução, ritmo e estratégia de prova, treinados juntos. O treino preferido do time.':'Once or twice a month at Tribeach: swim + run, bike + run or the full triathlon. Technique, pacing and race strategy, trained together. The team’s favorite session.',
'No Instagram':'On Instagram','Acompanhe o time':'Follow the team','CMTeam — o time':'CMTeam — the team','Carla Moreno — treinadora':'Carla Moreno — coach',
'Últimos posts do @cmteam':'Latest posts from @cmteam','Ver tudo no Instagram →':'See all on Instagram →',
'Para quem é':'Who it’s for','A CMTeam faz sentido para quem…':'CMTeam is right for you if you…',
'Não é para quem busca atalhos, fórmulas prontas ou motivação vazia.':'It is not for those looking for shortcuts, ready-made formulas or empty motivation.',
'quer entender o que está fazendo':'want to understand what you are doing','valoriza processo mais do que picos':'value process more than peaks',
'aceita que evolução real exige tempo, consistência e leitura correta do treino':'accept that real progress takes time, consistency and a proper reading of training',
'busca performance sem abrir mão de saúde, equilíbrio e longevidade esportiva':'seek performance without giving up health, balance and longevity in sport',
'Não buscamos a perfeição,':'We don’t chase perfection,','buscamos a':'we chase','constância.':'consistency.','Não corremos pra mostrar,':'We don’t run to show off,','corremos pra':'we run to','ser.':'become.',
'Provavelmente estamos falando a mesma língua.':'We’re probably speaking the same language.',
'Se você procura um trabalho consciente, estruturado e com visão de longo prazo, conte o seu objetivo para a gente.':'If you are looking for mindful, structured coaching with a long-term vision, tell us about your goal.',
'Seguir @cmteam':'Follow @cmteam','Telefone de contato':'Phone','Mensagem':'Message','Enviar mensagem':'Send message',
'Assessoria de triathlon, corrida e esportes de endurance. Carla Moreno Team — Miami e online, em mais de 25 países.':'Triathlon, running and endurance coaching. Carla Moreno Team — Miami and online, in more than 25 countries.',
'Navegação':'Navigation','Treinos em Miami':'Training in Miami','E-book grátis':'Free e-book','Contato':'Contact',
'A cabeça corre primeiro — grátis':'A cabeça corre primeiro — free',
}
ATTR={
'Assessoria de triathlon, corrida e trail que une a ciência de San Palma, criador do Método ECO, à experiência olímpica de Carla Moreno. Planilha individual no TrainingPeaks e suporte diário no WhatsApp. Online, de qualquer lugar, e presencial em Miami.':'Triathlon, running and trail coaching that brings together the science of San Palma, creator of the ECO Method, and the Olympic experience of Carla Moreno. An individual plan on TrainingPeaks and daily WhatsApp support. Online from anywhere, and in person in Miami.',
'Assessoria de triathlon, corrida e esportes de endurance. Metodologia ECO, acompanhamento próximo e visão de longo prazo — do iniciante ao competitivo. Miami e online.':'Triathlon, running and endurance coaching in Miami and online. The ECO Method, close guidance and a long-term vision — from first-timers to competitive athletes.',
'CMTeam — Aqui, cada treino tem motivo.':'CMTeam — Every session has a reason.',
'Fechar aviso':'Close','CMTeam — início':'CMTeam — home','Principal':'Main','Falar no WhatsApp':'Message us on WhatsApp','Fale conosco':'Contact us',
'Atletas da CMTeam pedalando à noite em Miami':'CMTeam athletes riding at night in Miami','Provas dos nossos atletas':'Our athletes’ races',
'Atletas da CMTeam reunidos após o treino em Miami':'CMTeam athletes together after a session in Miami','Coach da CMTeam orientando atletas antes do treino':'CMTeam coach briefing athletes before a session',
'San Palma, head coach da CMTeam':'San Palma, CMTeam head coach','Carla Moreno comemorando vitória em prova do circuito mundial de triathlon':'Carla Moreno celebrating a win at a world series triathlon',
'Capa do livro Nossa Jornada 2025, de San Palma':'Cover of Nossa Jornada 2025, by San Palma','Capa do livro Nossa Jornada 2026, de San Palma':'Cover of Nossa Jornada 2026, by San Palma','Capa do livro A cabeça corre primeiro, de San Palma':'Cover of A cabeça corre primeiro, by San Palma',
'Site CMTeam — e-book gratuito':'CMTeam website (EN) — free e-book','Seu nome':'Your name','Seu e-mail':'Your email',
'Contato pelo site CMTeam':'Contact from CMTeam website (EN)','Site CMTeam':'CMTeam website (EN)',
'com código do país, ex.: +55 11 99999-9999':'with country code, e.g. +1 305 555 0000','Conte seu objetivo, sua prova-alvo e sua rotina de treinos.':'Tell us your goal, your target race and your training routine.',

'Voltar ao topo':'Back to top','Formulário de contato':'Contact form','Ver no Instagram':'See on Instagram',
}
missing=[]
def txt(m):
    raw=m.group(1); k=raw.strip()
    if k in TEXT: return '>'+raw.replace(k,TEXT[k])+'<'
    return m.group(0)
# split out scripts/styles so we don't touch them in the text pass
parts=re.split(r'(<script[\s\S]*?</script>|<style[\s\S]*?</style>)',s)
for i,p in enumerate(parts):
    if p.startswith('<script') or p.startswith('<style'): continue
    p=re.sub(r'>([^<>]+)<',txt,p)
    def at(m):
        k=m.group(2)
        return m.group(1)+'="'+ATTR.get(k,k)+'"'
    p=re.sub(r'(alt|aria-label|placeholder|content|value|title)="([^"]*)"',at,p)
    parts[i]=p
s=''.join(parts)
# script / misc strings
REP=[
('Também é escritor: autor de <a href="#conteudo">Nossa Jornada 2025</a> e do livro de bolso <a href="#ebook">A cabeça corre primeiro</a>, escreve toda semana para os atletas do time, e o próximo livro, Nossa Jornada 2026, já está a caminho.','He is also a writer: author of <a href="#conteudo">Nossa Jornada 2025</a> and the pocket book <a href="#ebook">A cabeça corre primeiro</a>. He writes every week for the team’s athletes, and his next book, Nossa Jornada 2026, is on the way.'),
('data-goatcounter-click="','data-goatcounter-click="en-'),("path:'ebook-cadastro'","path:'en-ebook-cadastro'"),("path:'form-contato'","path:'en-form-contato'"),
('Preciso ser experiente para treinar com a CMTeam?','Do I need experience to train with CMTeam?'),
('Não. Treinamos do primeiro 5 km ao Ironman. O plano parte do seu momento, da sua rotina e do seu objetivo, seja ele começar, evoluir ou competir.','No. We coach everyone from a first 5K to Ironman. Your plan starts from where you are, your routine and your goal, whether that is getting started, improving or competing.'),
('Funciona se eu não moro em Miami?','Does it work if I don’t live in Miami?'),
('Sim. O acompanhamento online é completo: planilha individual no TrainingPeaks, feedback diário e a Carla no WhatsApp, de segunda a sábado. Temos atletas em mais de 25 países.','Yes. Online coaching is complete: an individual plan on TrainingPeaks, daily feedback and Carla on WhatsApp, Monday to Saturday. We have athletes in more than 25 countries.'),
('Quais modalidades vocês treinam?','Which sports do you coach?'),
('Triathlon, corrida de rua, trail e montanha e ultramaratona, sempre com a metodologia ECO.','Triathlon, road running, trail and mountain running, and ultramarathon, always with the ECO methodology.'),
('Como é o começo?','How does it start?'),
('Primeiro a gente conversa sobre seu objetivo e sua rotina. Depois você preenche um cadastro completo, com saúde, histórico e disponibilidade, e faz os testes para definição das suas zonas. A partir daí, sua planilha chega toda semana no TrainingPeaks.','First we talk about your goal and your routine. Then you fill in a complete intake form, covering health, history and availability, and do the tests to set your training zones. From then on, your plan arrives every week on TrainingPeaks.'),
('Preciso de relógio com GPS?','Do I need a GPS watch?'),
('Ajuda bastante, porque os treinos vão direto para o TrainingPeaks e o feedback fica mais preciso. Se você ainda não tem, a gente orienta na conversa.','It helps a lot, because your workouts sync straight to TrainingPeaks and the feedback is more precise. If you don’t have one yet, we will guide you when we talk.'),
('Quanto custa?','How much does it cost?'),
('Depende do formato, online ou presencial, e do que faz sentido para o seu objetivo. Chame a gente no WhatsApp e montamos juntos o melhor caminho.','It depends on the format, online or in person, and on what makes sense for your goal. Message us on WhatsApp and we will build the best path together.'),

('text=Ol%C3%A1!%20Quero%20treinar%20com%20a%20CMTeam.','text=Hi!%20I%27d%20like%20to%20train%20with%20CMTeam.'),
('text=Ol%C3%A1!%20Quero%20correr%20uma%20prova%20do%20calend%C3%A1rio%202027%20com%20a%20CMTeam.','text=Hi!%20I%27m%20planning%20to%20race%20one%20of%20the%202027%20team%20races%20with%20CMTeam.'),
('"description": "Assessoria de triathlon, corrida e trail que une a ciência de San Palma, criador do Método ECO, à experiência olímpica de Carla Moreno. Planilha individual no TrainingPeaks e suporte diário no WhatsApp. Online, de qualquer lugar, e presencial em Miami."','"description": "Triathlon, running and trail coaching that brings together the science of San Palma, creator of the ECO Method, and the Olympic experience of Carla Moreno. An individual plan on TrainingPeaks and daily WhatsApp support. Online from anywhere, and in person in Miami."'),
('"jobTitle": "Co-fundadora e Treinadora"','"jobTitle": "Co-founder & Coach"'),
('"jobTitle": "Co-fundador e Head Coach"','"jobTitle": "Co-founder & Head Coach"'),
('ECO <span style="color: #CB333B">|</span> Esforço Contínuo Ondulatório</h2>','ECO <span style="color: #CB333B">|</span> Esforço Contínuo Ondulatório</h2>\n<p style="margin: 0; font-size: 17px; line-height: 1.5; color: #B5B5B5"><em>Continuous Undulating Effort</em> — the methodology keeps its original Portuguese name.</p>'),
('<nav class="langsw" aria-label="Idioma / Language"><a href="./" class="on" aria-current="page" lang="pt-BR" title="Português" aria-label="Português"><svg class="flag" viewBox="0 0 28 20" aria-hidden="true"><rect width="28" height="20" rx="3" fill="#009C3B"></rect><path d="M14 3 25 10 14 17 3 10Z" fill="#FFDF00"></path><circle cx="14" cy="10" r="4.2" fill="#002776"></circle><path d="M10 9.2c2.6-.6 5.4-.3 7.9 1" stroke="#FFFFFF" stroke-width="1" fill="none"></path></svg></a><a href="en/" lang="en" hreflang="en" title="English" aria-label="English"><svg class="flag" viewBox="0 0 28 20" aria-hidden="true"><defs><clipPath id="fr"><rect width="28" height="20" rx="3"></rect></clipPath></defs><g clip-path="url(#fr)"><rect width="28" height="20" fill="#FFFFFF"></rect><g fill="#B22234"><rect y="0" width="28" height="1.54"></rect><rect y="3.08" width="28" height="1.54"></rect><rect y="6.15" width="28" height="1.54"></rect><rect y="9.23" width="28" height="1.54"></rect><rect y="12.31" width="28" height="1.54"></rect><rect y="15.38" width="28" height="1.54"></rect><rect y="18.46" width="28" height="1.54"></rect></g><rect width="12" height="10.77" fill="#3C3B6E"></rect></g></svg></a></nav>','<nav class="langsw" aria-label="Idioma / Language"><a href="../" lang="pt-BR" hreflang="pt-BR" title="Português" aria-label="Português"><svg class="flag" viewBox="0 0 28 20" aria-hidden="true"><rect width="28" height="20" rx="3" fill="#009C3B"></rect><path d="M14 3 25 10 14 17 3 10Z" fill="#FFDF00"></path><circle cx="14" cy="10" r="4.2" fill="#002776"></circle><path d="M10 9.2c2.6-.6 5.4-.3 7.9 1" stroke="#FFFFFF" stroke-width="1" fill="none"></path></svg></a><a href="./" class="on" aria-current="page" lang="en" title="English" aria-label="English"><svg class="flag" viewBox="0 0 28 20" aria-hidden="true"><defs><clipPath id="fr"><rect width="28" height="20" rx="3"></rect></clipPath></defs><g clip-path="url(#fr)"><rect width="28" height="20" fill="#FFFFFF"></rect><g fill="#B22234"><rect y="0" width="28" height="1.54"></rect><rect y="3.08" width="28" height="1.54"></rect><rect y="6.15" width="28" height="1.54"></rect><rect y="9.23" width="28" height="1.54"></rect><rect y="12.31" width="28" height="1.54"></rect><rect y="15.38" width="28" height="1.54"></rect><rect y="18.46" width="28" height="1.54"></rect></g><rect width="12" height="10.77" fill="#3C3B6E"></rect></g></svg></a></nav>'),
('<a href="en/" lang="en" style="color: #B5B5B5">English version</a>','<a href="../" lang="pt-BR" style="color: #B5B5B5">Versão em português</a>'),
('<html lang="pt-BR">','<html lang="en">'),
('<meta property="og:locale" content="pt_BR">','<meta property="og:locale" content="en_US">'),
('<link rel="canonical" href="https://cmteam.us/">','<link rel="canonical" href="https://cmteam.us/en/">'),
('<meta property="og:url" content="https://cmteam.us/">','<meta property="og:url" content="https://cmteam.us/en/">'),
('Preencha seu nome e um e-mail válido.','Please enter your name and a valid email.'),
('Liberando…','Unlocking…'),("btn.textContent='Baixar grátis'","btn.textContent='Get it free'"),
('Preencha todos os campos, com um e-mail válido.','Please fill in all fields with a valid email.'),
('Enviando…','Sending…'),("btn.textContent='Enviar mensagem'","btn.textContent='Send message'"),
('Mensagem enviada! Respondemos em breve.','Message sent! We will get back to you soon.'),
('Não foi possível enviar agora. Tente de novo ou fale com a gente pelo <a href="https://wa.me/13053959104">WhatsApp</a> ou por <a href="mailto:info@cmteam.us">info@cmteam.us</a>.','We could not send it right now. Please try again or reach us on <a href="https://wa.me/13053959104">WhatsApp</a> or at <a href="mailto:info@cmteam.us">info@cmteam.us</a>.'),
('text=Ol%C3%A1!%20Quero%20saber%20mais%20sobre%20a%20CMTeam.','text=Hi!%20I%27d%20like%20to%20know%20more%20about%20CMTeam.'),
('text=Ol%C3%A1!%20Quero%20ser%20avisado%20do%20lan%C3%A7amento%20do%20livro%20Nossa%20Jornada%202026.','text=Hi!%20Please%20let%20me%20know%20when%20Nossa%20Jornada%202026%20is%20released.'),
('src="img/','src="../img/'),('href="img/','href="../img/'),('href="livros/','href="../livros/'),('href="favicon','href="../favicon'),
]
for a,b in REP:
    if a not in s: missing.append(a[:60])
    s=s.replace(a,b)
open(DST,'w',encoding='utf-8').write(s)
print('missing script reps:',missing)
